language: node_js
node_js:
  - 12.16.3

branches:
  only:
  - master

services:
  - docker

install: skip

env:
  global:
  - ROOT_DIR=$PWD

before_script:
  - docker --version

jobs:
  exclude:
    - if: commit_message = "Add passing CI screenshot"
  include:
    - script: echo "Test Stage scripts go here."

    - stage: Build Docker Images
      name: Build API-Users
      script:
        - cd $ROOT_DIR/api-users
        - echo $PWD
        - docker --version
        - docker build -t udagram-users --rm .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag udagram-users scgerkin/udagram-users:latest
        - docker push scgerkin/udagram-users
    - # will use stage "Build Docker Images"
      name: Build API-Feed
      script:
        - cd $ROOT_DIR/api-feed
        - echo $PWD
        - docker --version
        - docker build -t udagram-feed --rm .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag udagram-feed scgerkin/udagram-feed:latest
        - docker push scgerkin/udagram-feed

after_success:
  - echo "This job was run successfully."
