language: node_js
node_js:
  - 12.16.3

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - cd api-users

script:
  - docker --version
  - docker build -t udagram-users --rm .
  - docker tag udagram-users scgerkin/udagram-users:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push scgerkin/udagram-users
