language: node_js
node_js:
  - 12.16.3

branches:
  only:
  - master

services:
  - docker

install: skip

env:
  global:
  - ROOT_DIR=$PWD

before_script:
  - docker --version

jobs:
  include:
    - script: echo "Test Stage scripts go here."

    - stage: Build Docker Images
      name: Build API-Users
      script:
        - cd $ROOT_DIR/api-users
        - echo $PWD
        - docker --version
        - docker build -t udagram-users --rm .
    - # will use stage "Build Docker Images"
      name: For future use with build
      script: echo "Additional jobs are denoted in this manner."

    - stage: Push Images
      name: Push API-Users
      script:
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker tag udagram-users scgerkin/udagram-users:latest
        - docker push scgerkin/udagram-users
    -
      name: For future use with push
      script: echo "Additional jobs are denoted in this manner."

after_success:
  - echo "This job was run successfully."
